#!/bin/bash
clear
echo "Created by Matthew Bierman, Lightning McQueens, Faith Lutheran Middle & High School, Las Vegas, NV, USA"
echo "Last Modified on Friday, January 21st, 2016, 7:20am"
echo "Comparative Script"

if [ -d "Desktop/Comparatives" ]
then
	diffuse Desktop/Comparatives/10periodic Desktop/OldComparatives/10periodic --tab Desktop/Comparatives/allports.log Desktop/OldComparatives/allports.log --tab Desktop/Comparatives/allservices.txt Desktop/OldComparatives/allservices.txt --tab Desktop/Comparatives/alltextfiles.txt Desktop/OldComparatives/alltextfiles.txt --tab Desktop/Comparatives/allusers.txt Desktop/OldComparatives/allusers.txt --tab Desktop/Comparatives/apache2.conf Desktop/OldComparatives/apache2.conf --tab Desktop/Comparatives/common-auth Desktop/OldComparatives/common-auth --tab Desktop/Comparatives/common-password Desktop/OldComparatives/common-password --tab Desktop/Comparatives/control-alt-delete.conf Desktop/OldComparatives/control-alt-delete.conf --tab Desktop/Comparatives/crontab.log Desktop/OldComparatives/crontab.log --tab Desktop/Comparatives/group Desktop/OldComparatives/group --tab Desktop/Comparatives/hosts Desktop/OldComparatives/hosts --tab Desktop/Comparatives/initctl-running.txt Desktop/OldComparatives/initctl-running.txt --tab Desktop/Comparatives/lightdm.conf Desktop/OldComparatives/lightdm.conf --tab Desktop/Comparatives/listeningports.log Desktop/OldComparatives/listeningports.log --tab Desktop/Comparatives/login.defs Desktop/OldComparatives/login.defs --tab Desktop/Comparatives/manuallyinstalled.log Desktop/OldComparatives/manuallyinstalled.log --tab Desktop/Comparatives/my.cnf Desktop/OldComparatives/my.cnf --tab Desktop/Comparatives/packages.log Desktop/OldComparatives/packages.log --tab Desktop/Comparatives/passwd Desktop/OldComparatives/passwd --tab Desktop/Comparatives/processes.log Desktop/OldComparatives/processes.log --tab Desktop/Comparatives/rc.local Desktop/OldComparatives/rc.local --tab Desktop/Comparatives/smb.conf Desktop/OldComparatives/smb.conf --tab Desktop/Comparatives/socketconnections.log Desktop/OldComparatives/socketconnections.log --tab Desktop/Comparatives/sources.list Desktop/OldComparatives/sources.list --tab Desktop/Comparatives/sshd_config Desktop/OldComparatives/sshd_config --tab Desktop/Comparatives/sudoers Desktop/OldComparatives/sudoers --tab Desktop/Comparatives/sysctl.conf Desktop/OldComparatives/sysctl.conf --tab Desktop/Comparatives/tree.txt Desktop/OldComparatives/tree.txt --tab Desktop/Comparatives/vsftpd.conf Desktop/OldComparatives/vsftpd.conf
fi